<a href="https://colab.research.google.com/github/jmmotta/CIAA-MatiasFerraro/blob/master/bds_ejercicio_002.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
<img src="https://www.python.org/static/community_logos/python-powered-h-70x91.png">
</p>

# â˜¯ <font color="DeepPink">**Actividad 002**</font>

## ðŸ”¹ <font color="DeepPink">**Habilitando Pandas**</font>

In [1]:
# mi cÃ³digo aquÃ­
import pandas as pd
import numpy as np

## ðŸ”¹ <font color="DeepPink">**Datos**</font>

In [4]:
datos =  pd.read_csv("https://raw.githubusercontent.com/cristiandarioortegayubro/base/main/dataset/departamento.csv")

In [5]:
datos.shape

(2232, 8)

In [6]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2232 entries, 0 to 2231
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   M2          2232 non-null   int64
 1   AMBIENTES   2232 non-null   int64
 2   ANTIGUEDAD  2232 non-null   int64
 3   BAÃ‘OS       2232 non-null   int64
 4   LATITUD     2232 non-null   float64
 5   LONGITUD    2232 non-null   float64
 6   COMUNA      2232 non-null   object
 7   DOLARES     2232 non-null   int64
dtypes: float64(2), int64(5), object(1)
memory usage: 139.6+ KB

## ðŸ”¹ <font color="DeepPink">**CreaciÃ³n del DataFrame**</font>

<p>
<font color="DeepPink">

> **Generar el dataframe**
</font>
</p>

In [9]:
dtype(datos)

NameError: name 'dtype' is not defined

In [14]:
datos.index

RangeIndex(start=0, stop=2232, step=1)

## ðŸ”¹ <font color="DeepPink">**A divertirse... ðŸ˜ƒ**</font>

<p>
<font color="DeepPink">

> **Visualizar solamente la columna (serie) dolares... y creamos esa serie...**
</font>
</p>

In [15]:
datos.iloc[:,7]

0       225000
1       140000
2       154000
3        75000
4       149900
         ...
2227    165000
2228     79900
2229    520000
2230    132000
2231    179000
Name: DOLARES, Length: 2232, dtype: int64

In [16]:
datos["DOLARES"]

0       225000
1       140000
2       154000
3        75000
4       149900
         ...
2227    165000
2228     79900
2229    520000
2230    132000
2231    179000
Name: DOLARES, Length: 2232, dtype: int64

In [17]:
VALOR_DEPTO = datos["DOLARES"]

In [18]:
VALOR_DEPTO

0       225000
1       140000
2       154000
3        75000
4       149900
         ...
2227    165000
2228     79900
2229    520000
2230    132000
2231    179000
Name: DOLARES, Length: 2232, dtype: int64

In [21]:
VALOR_DEPTO.info()

<class 'pandas.core.series.Series'>
RangeIndex: 2232 entries, 0 to 2231
Series name: DOLARES
Non-Null Count  Dtype
--------------  -----
2232 non-null   int64
dtypes: int64(1)
memory usage: 17.6 KB

In [26]:
type(VALOR_DEPTO)

pandas.core.series.Series

<p>
<font color="DeepPink">

> **Buscamos pasar la serie anterior a dataframe...usando el metodo ```to.frame()```**
</font>
</p>

In [27]:
df = VALOR_DEPTO.to_frame()

In [28]:
df

      DOLARES
0      225000
1      140000
2      154000
3       75000
4      149900
...       ...
2227   165000
2228    79900
2229   520000
2230   132000
2231   179000

[2232 rows x 1 columns]

<p>
<font color="DeepPink">

> **Mostrar en pantalla ```print()``` los $m^2$ de los departamentos...**
</font>
</p>

In [30]:
print(datos["M2"])

0        81
1        69
2        75
3        42
4        90
       ...
2227     88
2228     35
2229    117
2230     69
2231     73
Name: M2, Length: 2232, dtype: int64

<p>
<font color="DeepPink">

> **Crear una nueva columna llamada PAIS y rellenarla con "Argentina"...**
</font>
</p>

In [36]:
pais = ["Argentina"]*2232

In [37]:
len(pais)

2232

In [39]:
type(pais)

list

In [42]:
datos["PAIS"]=pais

In [43]:
datos

,M2,AMBIENTES,ANTIGUEDAD,BAÃ‘OS,LATITUD,LONGITUD,COMUNA,DOLARES,PAIS
0,81,3,4,1,-34.581078,-58.449433,COMUNA 13,225000,Argentina
1,69,3,20,1,-34.623129,-58.439338,COMUNA 06,140000,Argentina
2,75,3,20,1,-34.604972,-58.421278,COMUNA 05,154000,Argentina
3,42,2,40,1,-34.604725,-58.399524,COMUNA 03,75000,Argentina
4,90,3,1,1,-34.623390,-58.504401,COMUNA 10,149900,Argentina
...,...,...,...,...,...,...,...,...,...
2227,88,4,20,2,-34.550152,-58.470136,COMUNA 13,165000,Argentina
2228,35,1,35,1,-34.602256,-58.429315,COMUNA 05,79900,Argentina
2229,117,3,10,2,-34.620314,-58.365451,COMUNA 01,520000,Argentina
2230,69,4,40,1,-34.628533,-58.427748,COMUNA 07,132000,Argentina
2231,73,4,50,2,-34.596659,-58.378396,COMUNA 01,179000,Argentina

<p>
<font color="DeepPink">

> **Ahora una nueva columna llamada CONTINENTE y rellenarla con "America"...**
</font>
</p>

In [45]:
cont = ["America"]*2232

In [46]:
datos["CONTINENTE"]=cont

In [47]:
datos

,M2,AMBIENTES,ANTIGUEDAD,BAÃ‘OS,LATITUD,LONGITUD,COMUNA,DOLARES,PAIS,CONTINENTE
0,81,3,4,1,-34.581078,-58.449433,COMUNA 13,225000,Argentina,America
1,69,3,20,1,-34.623129,-58.439338,COMUNA 06,140000,Argentina,America
2,75,3,20,1,-34.604972,-58.421278,COMUNA 05,154000,Argentina,America
3,42,2,40,1,-34.604725,-58.399524,COMUNA 03,75000,Argentina,America
4,90,3,1,1,-34.623390,-58.504401,COMUNA 10,149900,Argentina,America
...,...,...,...,...,...,...,...,...,...,...
2227,88,4,20,2,-34.550152,-58.470136,COMUNA 13,165000,Argentina,America
2228,35,1,35,1,-34.602256,-58.429315,COMUNA 05,79900,Argentina,America
2229,117,3,10,2,-34.620314,-58.365451,COMUNA 01,520000,Argentina,America
2230,69,4,40,1,-34.628533,-58.427748,COMUNA 07,132000,Argentina,America
2231,73,4,50,2,-34.596659,-58.378396,COMUNA 01,179000,Argentina,America

<p>
<font color="DeepPink">

> **Generar una columna que se llame PESOS cuyo valor sea DOLARES $\times$ $300$...**
</font>
</p>

In [48]:
pesos = [0] * 2232

In [49]:
datos["PESOS"] = pesos
datos["PESOS"] = datos["DOLARES"]*300

In [50]:
datos

,M2,AMBIENTES,ANTIGUEDAD,BAÃ‘OS,LATITUD,LONGITUD,COMUNA,DOLARES,PAIS,CONTINENTE,PESOS
0,81,3,4,1,-34.581078,-58.449433,COMUNA 13,225000,Argentina,America,67500000
1,69,3,20,1,-34.623129,-58.439338,COMUNA 06,140000,Argentina,America,42000000
2,75,3,20,1,-34.604972,-58.421278,COMUNA 05,154000,Argentina,America,46200000
3,42,2,40,1,-34.604725,-58.399524,COMUNA 03,75000,Argentina,America,22500000
4,90,3,1,1,-34.623390,-58.504401,COMUNA 10,149900,Argentina,America,44970000
...,...,...,...,...,...,...,...,...,...,...,...
2227,88,4,20,2,-34.550152,-58.470136,COMUNA 13,165000,Argentina,America,49500000
2228,35,1,35,1,-34.602256,-58.429315,COMUNA 05,79900,Argentina,America,23970000
2229,117,3,10,2,-34.620314,-58.365451,COMUNA 01,520000,Argentina,America,156000000
2230,69,4,40,1,-34.628533,-58.427748,COMUNA 07,132000,Argentina,America,39600000
2231,73,4,50,2,-34.596659,-58.378396,COMUNA 01,179000,Argentina,America,53700000

<p>
<font color="DeepPink">

> **Mostrar el resumen estadistico descriptivo del dataframe...**
</font>
</p>

In [53]:
datos.describe().round(2).T

,count,mean,std,min,25%,50%,75%,max
M2,2232.0,79.40,58.98,15.00,44.00,64.00,90.00,7.300000e+02
AMBIENTES,2232.0,2.81,1.11,1.00,2.00,3.00,3.00,1.000000e+01
ANTIGUEDAD,2232.0,24.63,18.41,1.00,9.00,20.00,40.00,1.100000e+02
BAÃ‘OS,2232.0,1.43,0.72,1.00,1.00,1.00,2.00,6.000000e+00
LATITUD,2232.0,-34.59,0.02,-34.68,-34.61,-34.59,-34.58,-3.454000e+01
LONGITUD,2232.0,-58.43,0.03,-58.53,-58.45,-58.42,-58.40,-5.835000e+01
DOLARES,2232.0,206014.01,186368.30,7428.00,98375.00,146000.00,235750.00,1.800000e+06
PESOS,2232.0,61804203.63,55910491.15,2228400.00,29512500.00,43800000.00,70725000.00,5.400000e+08

<p>
<font color="DeepPink">

> **Â¿Cual es la media de latitud y longitud?...**
</font>
</p>

In [ ]:
# mi cÃ³digo aquÃ­

## ðŸ”¹ <font color="DeepPink">**Un poco mÃ¡s dificil... ðŸ˜ˆ**</font>

---
<p>
<font color="DeepPink">

ðŸ‘€ **Para los siguientes puntos se puede consultar la documentaciÃ³n tÃ©cnica de Pandas...**
</font>
</p>

---

<p>
<font color="DeepPink">

> **Verificar si existen datos nulos en el dataframe...**
</font>
</p>

In [57]:
datos.isna().any()

M2            False
AMBIENTES     False
ANTIGUEDAD    False
BAÃ‘OS         False
LATITUD       False
LONGITUD      False
COMUNA        False
DOLARES       False
PAIS          False
CONTINENTE    False
PESOS         False
dtype: bool

<p>
<font color="DeepPink">

> **Â¿Cuantos departamentos hay por comuna?...**
</font>
</p>

In [ ]:
# mi cÃ³digo aquÃ­

<p>
<font color="DeepPink">

> **Â¿Cuantos ambientes tiene los departamentos de la comuna 14?...**
</font>
</p>

In [ ]:
# mi cÃ³digo aquÃ­

<br>
<br>
<p align="center"><b>
ðŸ’—
<font color="DeepPink">
Hemos llegado al final de nuestro colab, a seguir codeando...
</font>